COMMENT ON COLUMN "users"."google_id" IS NULL;
COMMENT ON COLUMN "users"."facebook_id" IS NULL;
DROP INDEX IF EXISTS users_owner_idx;
DROP TABLE IF EXISTS "users";
REVOKE ALL PRIVILEGES ON DATABASE userdb FROM userdb_user;
DROP DATABASE IF EXISTS userdb;
DROP ROLE IF EXISTS userdb_user;
