// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) VALUES ($1)
RETURNING id, name, image_count, subscribed, created_at
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageCount,
		&i.Subscribed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, image_count, subscribed, created_at FROM users
WHERE id = $1
LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageCount,
		&i.Subscribed,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, name, image_count, subscribed, created_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageCount,
		&i.Subscribed,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, image_count, subscribed, created_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageCount,
			&i.Subscribed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageCount = `-- name: UpdateImageCount :one
UPDATE users
SET image_count = image_count + $1
WHERE id = $2
RETURNING id, name, image_count, subscribed, created_at
`

type UpdateImageCountParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateImageCount(ctx context.Context, arg UpdateImageCountParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateImageCount, arg.Amount, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageCount,
		&i.Subscribed,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubscribed = `-- name: UpdateSubscribed :one
UPDATE users
SET subscribed = $2
WHERE id = $1
RETURNING id, name, image_count, subscribed, created_at
`

type UpdateSubscribedParams struct {
	ID         int64 `json:"id"`
	Subscribed bool  `json:"subscribed"`
}

func (q *Queries) UpdateSubscribed(ctx context.Context, arg UpdateSubscribedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateSubscribed, arg.ID, arg.Subscribed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageCount,
		&i.Subscribed,
		&i.CreatedAt,
	)
	return i, err
}
